[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
cache_path  = 'forge-cache'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
test = 'test'
solc = '0.8.26'
fs_permissions = [{ access = 'read', path = './' }, { access = 'read-write', path = './deploy-out' }]
evm_version = 'cancun'